spring:
  application:
    name: DBS_CA2_data_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbs_ca2
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true